apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : myapp1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app1
  source:
    path   : "HelmCharts/helm-guestbook"
    repoURL: "https://github.com/GeorgyPzk/argocdpub.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yaml

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   